#!/usr/bin/env bash
set -e # halt script on error

JEKYLL_OUTPUT_FILE=jekyll-build-output.txt

# Do a Jekyll build to create the site.
bundle exec jekyll build 2>&1 | tee ${JEKYLL_OUTPUT_FILE}

# If Jekll build had an error, then exit and propagate the status.
JEKYLL_EXIT_CODE=${PIPESTATUS[0]}
if [ "${JEKYLL_EXIT_CODE}" -ne "0" ]
then
    echo "ERROR: Jekyll build failed. Exiting with status ${JEKYLL_EXIT_CODE}."
    exit ${JEKYLL_EXIT_CODE}
fi

# If Jekll build had warning, then exit.
if grep -q -i "Build Warning" ${JEKYLL_OUTPUT_FILE}
then
    echo "ERROR: Jekyll build gave a warning. Exiting."
    exit 1
fi

# Check the site with html-proof
bundle exec htmlproof ./_site